version: 2.1

parameters:
  medium:
    type: string
    default: medium
  large:
    type: string
    default: large
  xlarge:
    type: string
    default: xlarge
  twoxlarge:
    type: string
    default: 2xlarge

orbs:
  windows: circleci/windows@5.0

executors:
  # The default docker image used in the main-workflow
  rust-docker:
     docker:
      - image: cimg/rust:1.88.0 # Attention - Change the MSRV in Cargo.toml and rust-toolchain as well

commands:
  check_windows:
    description: "Runs cargo check on Windows"
    parameters:
      workspace_member:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}i
            - cargo-cache-{{ arch }}- # fallback to an older version
      - run:
          name: "Install Rust and run cargo check"
          command: |
            $ProgressPreference = "SilentlyContinue"
            # Remove the circleci installed rustc.
            choco uninstall rust
            # Install llvm (libclang for rocksdb).
            choco install llvm -y 
            refreshenv
            # Install rust with rustup.
            Invoke-WebRequest -Uri "https://win.rustup.rs/" -OutFile "C:\rustup-init.exe"
            & C:\rustup-init.exe -y --default-toolchain "1.88.0-x86_64-pc-windows-msvc" --no-modify-path --profile minimal # Attention - Change the MSRV in Cargo.toml and rust-toolchain as well
            $Env:Path += ";$Env:USERPROFILE\.cargo\bin"
            # Verify the installation.
            cargo --version --verbose
            rustc --version | Out-File -FilePath "rust-version"
            if (!(Test-Path "Cargo.lock" -PathType Leaf)) {
                cargo generate-lockfile
            }
            cd << parameters.workspace_member >>
            cargo check --examples --benches --tests
      - save_cache:
          paths:
            - C:\Users\circleci\.cargo\registry
            - C:\Users\circleci\.cargo\git
            - target
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

  setup_environment:
    description: "Setup testing environment"
    parameters:
      cache_key:
        type: string
        default: v3.3.1-rust-1.88.0-snarkos-stable-cache
    steps:
      - run:
          name: Set environment variables
          command: |
            # CircleCI runs a new shell for every step, so exported variables are lost
            # This workaround is suggested here: https://circleci.com/docs/env-vars/#parameters-and-bash-environment
            echo 'set -e' >> "$BASH_ENV"
            echo 'export SCCACHE_CACHE_SIZE=1G' >> "$BASH_ENV"
            echo 'export SCCACHE_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"' >> "$BASH_ENV"
            echo 'export RUSTC_WRAPPER="$CIRCLE_WORKING_DIRECTORY/.bin/sccache"' >> "$BASH_ENV"
            # Disable incremental builds so that sccache works as expected
            echo 'export CARGO_INCREMENTAL=0' >> "$BASH_ENV"

      - run:
          name: Install sccache
          command: |
            mkdir -p "$CIRCLE_WORKING_DIRECTORY/.bin"
            export SCCACHE_VERSION=v0.10.0
            export SCCACHE_PKG="sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl"
            wget "https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/$SCCACHE_PKG.tar.gz"
            tar -C "$CIRCLE_WORKING_DIRECTORY/.bin" -xvf "$SCCACHE_PKG.tar.gz"
            mv "$CIRCLE_WORKING_DIRECTORY/.bin/$SCCACHE_PKG/sccache" "$CIRCLE_WORKING_DIRECTORY/.bin/sccache"
            rm -rf "$CIRCLE_WORKING_DIRECTORY/.cargo/registry"

      - run:
          name: Install debian packages
          command: |
            DEBIAN_FRONTEND=noninteractive sudo apt-get update
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev libssl-dev
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends clang llvm-dev llvm pkg-config xz-utils make libssl-dev libssl-dev
      - fetch_cache:
          cache_key: << parameters.cache_key >>

  fetch_cache:
    description: "Fetch the cached data"
    parameters:
      cache_key:
        type: string
    steps:
      - run:
          name: Generate daily cache key
          command: |
            CACHE_DATE=$(date +%Y-%m-%d)
            echo "Cache date is $CACHE_DATE"
            echo "$CACHE_DATE" >> cache-key-suffix
      - restore_cache:
          keys:
            - << parameters.cache_key >>-{{ checksum "cache-key-suffix" }}
            - << parameters.cache_key >>-  # fallback to a different day

  store_cache:
    description: "Store the updated cache (once per day)"
    parameters:
      cache_key:
        type: string
    steps:
      - save_cache:
          key: << parameters.cache_key >>-{{ checksum "cache-key-suffix" }}
          paths:
            - .cache/sccache
            - .cargo

  clear_environment:
    description: "Clear environment"
    parameters:
      cache_key:
        type: string
        default: v3.3.1-rust-1.88.0-snarkos-stable-cache
    steps:
      - run:
          name: Show sccache statistics
          command: $CIRCLE_WORKING_DIRECTORY/.bin/sccache -s
      - store_cache:
          cache_key: << parameters.cache_key >>

  run_test:
    description: "Build and run tests"
    parameters:
      workspace_member:
        type: string
      flags:
        type: string
        default: ""
    steps:
      - checkout
      - setup_environment:
          cache_key:  v4.0.0-rust-1.88.0-<< parameters.workspace_member >>-cache
      - run:
          name: Build Tests
          timeout: 15m
          command: cargo test --package=<< parameters.workspace_member >> --no-run << parameters.flags >>
      - run:
          name: Run Tests
          timeout: 15m
          command: cargo test --package=<< parameters.workspace_member >> << parameters.flags >>
      - clear_environment:
          cache_key: v4.0.0-rust-1.88.0-<< parameters.workspace_member >>-cache

  run_devnet:
    description: "Run devnet for integration testing"
    parameters:
      workspace_member:
        type: string
      cache_key:
        type: string
      validators:
        type: integer
        default: 4
      clients:
        type: integer
        default: 2
      network_id:
        type: integer
        default: 0
      min_height:
        type: integer
        default: 45
    steps:
      - checkout
      - setup_environment:
          cache_key: << parameters.cache_key >>
      - run:
          name: "Install snarkos"
          command: |
            cargo install --locked --path .
      - run:
          name: "Run DB backup test"
          timeout: 10m  # Allow 10 minutes total
          command: |
            ./.circleci/db_backup_ci.sh # run the db checkpoint test script first, and clean the dev ledgers afterwards
            snarkos clean --dev 0
            snarkos clean --dev 1
            snarkos clean --dev 2
            snarkos clean --dev 3
      - run:
          name: "Run block advancement test"
          imeout: 20m  # Allow 20 minutes total
          command: |
            ./.circleci/devnet_ci.sh << parameters.validators >> << parameters.clients >> << parameters.network_id >> << parameters.min_height >>
      - clear_environment:
          cache_key: << parameters.cache_key >>

  install_rust_nightly:
    description: "Install Rust nightly toolchain"
    steps:
      - run: rustup toolchain install nightly-x86_64-unknown-linux-gnu

jobs:
  snarkos:
    executor: rust-docker
    resource_class: << pipeline.parameters.twoxlarge >>
    steps:
      - run_test:
          workspace_member: snarkos

  account:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_test:
          workspace_member: snarkos-account

  cli:
    executor: rust-docker
    resource_class: << pipeline.parameters.twoxlarge >>
    steps:
      - run_test:
          workspace_member: snarkos-cli

  node:
    executor: rust-docker
    resource_class: << pipeline.parameters.twoxlarge >>
    steps:
      - run_test:
          workspace_member: snarkos-node

  node-bft:
    executor: rust-docker
    resource_class: << pipeline.parameters.twoxlarge >>
    steps:
      - run_test:
          workspace_member: snarkos-node-bft

  node-bft-events:
    executor: rust-docker
    resource_class: << pipeline.parameters.large >>
    steps:
      - run_test:
          workspace_member: snarkos-node-bft-events

  node-bft-ledger-service:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_test:
          workspace_member: snarkos-node-bft-ledger-service

  node-bft-storage-service:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_test:
          workspace_member: snarkos-node-bft-storage-service

  node-cdn:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_test:
          workspace_member: snarkos-node-cdn

  node-consensus:
    executor: rust-docker
    resource_class: << pipeline.parameters.large >>
    steps:
      - run_test:
          workspace_member: snarkos-node-consensus

  node-rest:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_test:
          workspace_member: snarkos-node-rest

  node-router:
    executor: rust-docker
    resource_class: << pipeline.parameters.large >>
    steps:
      - run_test:
          workspace_member: snarkos-node-router

  node-router-messages:
    executor: rust-docker
    resource_class: << pipeline.parameters.large >>
    steps:
      - run_test:
          workspace_member: snarkos-node-router-messages

  node-sync:
    executor: rust-docker
    resource_class: << pipeline.parameters.xlarge >>
    steps:
      - run_test:
          workspace_member: snarkos-node-sync

  node-sync-communication-service:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_test:
          workspace_member: snarkos-node-sync-communication-service

  node-sync-locators:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_test:
          workspace_member: snarkos-node-sync-locators

  node-tcp:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - run_test:
          workspace_member: snarkos-node-tcp

  devnet-test:
    executor: rust-docker
    resource_class: << pipeline.parameters.xlarge >>
    steps:
      - run_devnet:
          workspace_member: .
          cache_key: v4.0.0-rust-1.88.0-devnet-test-cache

  # Check crates that do not have any tests individually
  check-other-crates:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - checkout
      - setup_environment:
          cache_key: v3.3.1-rust-1.88.0-check-other-crates-cache
      - run:
          name: Check snarkos-node-metrics crate
          no_output_timeout: 10m
          command: cargo check --package=snarkos-node-metrics --all-features
      - run:
          name: Check snarkos-display crate
          no_output_timeout: 10m
          command: cargo check --package=snarkos-node-metrics --all-features
      - clear_environment:
          cache_key: v3.3.1-rust-1.88.0-check-other-crates-cache

  check-fmt:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - checkout
      - install_rust_nightly
      - setup_environment:
          cache_key: v4.0.0-rust-1.88.0-fmt-cache
      - run:
          name: Check style
          no_output_timeout: 35m
          command: cargo +nightly fmt --all -- --check
      - clear_environment:
          cache_key: v4.0.0-rust-1.88.0-fmt-cache

  check-unused-dependencies:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - checkout
      - setup_environment:
          cache_key: v4.0.0-rust-1.88.0-machete-cache
      - run:
          name: Check for unused dependencies
          no_output_timeout: 10m
          command: |
            cargo install cargo-machete@0.7.0
            cargo machete
      - clear_environment:
          cache_key: v4.0.0-rust-1.88.0-machete-cache

  check-cargo-audit:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - checkout
      - setup_environment:
          cache_key: v4.0.0-rust-1.88.0-cargo-audit-cache
      - run:
          name: Check for security vulnerabilities
          no_output_timeout: 10m
          command: |
            cargo install cargo-audit@0.21.2 --locked
            cargo audit -D warnings
      - clear_environment:
          cache_key: v4.0.0-rust-1.88.0-cargo-audit-cache

  check-clippy:
    executor: rust-docker
    resource_class: << pipeline.parameters.medium >>
    steps:
      - checkout
      - setup_environment:
          cache_key: v4.0.O-rust-1.88.0-clippy-cache
      - run:
          name: Check lint
          no_output_timeout: 35m
          command: |
            cargo clippy --workspace --all-targets -- -D warnings
            cargo clippy --workspace --all-targets --all-features -- -D warnings
      - clear_environment:
          cache_key: v4.0.0-rust-1.88.0-clippy-cache

  verify-windows:
    executor:
      name: windows/default
      size: xlarge
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    parameters:
      workspace_member:
        type: string
    steps:
      - check_windows:
          workspace_member: << parameters.workspace_member >>

workflows:
  version: 2

  main-workflow:
    jobs:
      - snarkos
      - account
      - cli
      - node
      - node-bft
      - node-bft-events
      - node-bft-ledger-service
      - node-bft-storage-service
      - node-cdn
      - node-consensus
      - node-rest
      - node-router
      - node-router-messages
      - node-sync
      - node-sync-communication-service
      - node-sync-locators
      - node-tcp
      - check-fmt
      - check-clippy
      - check-unused-dependencies
      - check-cargo-audit
      - check-other-crates
      - devnet-test

  windows-workflow:
    jobs:
      - verify-windows:
          matrix:
            parameters:
              workspace_member: [
                account,
                cli,
                display,
                node
              ]
